name: Cron API Call

on:
  schedule:
    - cron: '*/1 * * * *'   # Toutes les 1 minutes (UTC)
  workflow_dispatch:        # Permet de lancer manuellement si besoin

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run API Call
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python run_api_call.py
